docs: add mitigation section for internal resolution error
arethetypeswrong/arethetypeswrong.github.io pull request #220
Opened 2024-11-05 15:59 UTC by MilanKovacic

- Added mitigation section for internal resolution error documentation

2024-11-05 16:02 UTC, MilanKovacic commented
Hi @andrewbranch, if you have a moment, could you please take a look?

2024-11-10 20:56 UTC, andrewbranch requested changes
Thanks for giving this a shot, but I don’t think the content is quite bulletproof. There’s quite a lot of subtlety with this stuff that makes it hard to be pithy and accurate at the same time. Maybe a very brief sentence about type checking with appropriate compiler options, along with a link to https://www.typescriptlang.org/docs/handbook/modules/guides/choosing-compiler-options.html#im-writing-a-library would be best.

2024-11-10 20:56 UTC, andrewbranch commented on docs/problems/InternalResolutionError.md
> +`node16` module resolution requires explicit file extensions for relative imports.
This isn’t true in general; it’s only true for ESM-mode files

2024-11-10 20:56 UTC, andrewbranch commented on docs/problems/InternalResolutionError.md
> +3. Use independent tools such as [API Extractor](https://api-extractor.com/pages/setup/configure_rollup/) to generate a single declaration file.
I don’t really agree with this advice. Ideally, declaration files should only be bundled when the JavaScript files are bundled.

2024-12-06 20:23 UTC, andrewbranch commented
Closing for housekeeping for now, feel free to open a new one with updates

2024-12-06 20:23 UTC, closed without merging